# Generated by Django 5.2 on 2025-05-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prioridade',
        ),
    ]
