# Generated by Django 5.2 on 2025-05-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_descricao_tecnico_ticket_tecnico_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='categoria',
        ),
    ]
